### ISSUE TITLE
Use an instance from searx.space

### ISSUE THREAD

**Issue by Eloitor** [Hedreon/SearXNG-Search#2]
The current instance searx.org is offline:

![image](https://user-images.githubusercontent.com/17795572/206046729-edfbe6db-f156-406f-a00a-8379a6552514.png)

searx.org is not listed in searx.space because of cloudflare. It would be better to use an instance from the list.

**Comment by Hedreon** [comment]
but oke

**Comment by Eloitor** [comment]
No, there isn't an official one. There is the public list of instances, and they avoid the ones using cloudflare. So searx.org is not there.

**Comment by Hedreon** [comment]
> No, there isn't an official one. There is the public list of instances, and they avoid the ones using cloudflare. So searx.org is not there.

Right.

**Comment by Hedreon** [comment]
Well, I did the commit, but I haven't pushed an update out to firefox yet.

**Comment by Hedreon** [comment]
> Well, I did the commit, but I haven't pushed an update out to firefox yet, so I'm going to push an update now.

And... I forgot, so I WILL publish it afterschool, I swaer

**Comment by Hedreon** [comment]
I did not. Now I will
![image](https://user-images.githubusercontent.com/39467046/206880034-4a2608c6-e03f-4b4b-92b4-b6bae7618ac2.png)
